//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mustafina_language
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentByService
    {
        public int ID { get; set; }
        public int ClientServiceID { get; set; }
        public string DocumentPath { get; set; }
    
        public virtual ClientService ClientService { get; set; }
    }
}
