//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mustafina_language
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.TagOfClient = new HashSet<TagOfClient>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Color { get; set; }
    
        public virtual ICollection<TagOfClient> TagOfClient { get; set; }
    }
}
